# Site settings
title: Ash Smith
email: hello@ashsmith.io
description: "Magento Developer @ Meanbee"
baseurl: ""
url: "https://www.ashsmith.io"
google_analytics: UA-10830573-3
disqus_shortname: meteorify
google_verify: "aFObGx6hPm-RcrM66qK0yFp-u1GSCHyHXAgt4dWRIzM"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
exclude: [ node_modules, sass, Gemfile, Gemfile.lock, Gulpfile.js, package.json, README.md, docker-compose.yml, nginx.conf, docker, Jenkinsfile, build.sh, buildspec.yml]
gems:
  - jekyll-gist
