# Site settings
title: Ash Smith
email: me@ashsmith.io
description: "Magento Developer @ Meanbee"
baseurl: ""
url: "http://ashsmith.io"
google_analytics: UA-10830573-3
disqus_shortname: meteorify
google_verify: "aFObGx6hPm-RcrM66qK0yFp-u1GSCHyHXAgt4dWRIzM"

links:
    - title: Home
      url: /
    # - title: About
    #   url: /about/
    # - title: Contact
    #   url: /contact/

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
