version: 0.2

phases:

  pre_build:
    commands:
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
      - aws configure set preview.cloudfront true
  build:
    commands:
      - docker run -v $CODEBUILD_SRC_DIR:/usr/src/app $DOCKER_CONTAINER
  post_build:
    commands:
      - cd _site && aws s3 sync --delete --region $AWS_S3_REGION ./ s3://$AWS_S3_BUCKET/
      - aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION --paths '/*'

