version: "2"

services:
    # build_server:
    #   build: docker/build_server
    #   volumes:
    #     - ./:/usr/src/app
    node:
      build: docker/node
      volumes:
        - ./blog:/usr/src/app
    gatsby:
      build: docker/node
      volumes:
        - ./blog:/usr/src/app
      command: gatsby develop -H 0.0.0.0 -p 8000
      ports:
        - "8000:8000"